services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: dorriss-blog:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: dorriss-blog:latest
