spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dorrissBlog
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      format_sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
